// 由 scripts/bundle-migrations.ts 生成,勿手改;重新生成:pnpm --filter @musefold/desktop-db run db:bundle
import type { MigrationMeta } from 'drizzle-orm/migrator';

export const DESKTOP_MIGRATIONS: MigrationMeta[] = [
  {
    sql: [
      '-- v2.5 baseline:core legacy 迁移链(0001→0020)终态的忠实导出(sqlite_master)。\n-- 手工审阅并由 __tests__/takeover.test.ts 与 legacy 链逐对象比对;含 CHECK 约束、\n-- partial/DESC 索引与 prompts_fts 虚表(这些无法由 drizzle-kit 表达,meta 快照有意不含)。\n-- 本文件只在全新空库上执行;既有库经 fake-apply 直接标记为已应用(见 src/takeover.ts)。\n\nCREATE TABLE folders (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  parent_id TEXT REFERENCES folders(id) ON DELETE CASCADE,\n  sort_order INTEGER DEFAULT 0,\n  created_at INTEGER NOT NULL\n);',
      'CREATE TABLE prompts (\n  id TEXT PRIMARY KEY,\n  title TEXT NOT NULL,\n  description TEXT,\n  content TEXT NOT NULL,\n  content_negative TEXT,\n  folder_id TEXT REFERENCES folders(id) ON DELETE SET NULL,\n  model_id TEXT,\n  params TEXT,\n  preview_image_path TEXT,\n  rating INTEGER DEFAULT 0,\n  is_pinned INTEGER DEFAULT 0,\n  pin_order INTEGER,\n  usage_count INTEGER DEFAULT 0,\n  last_used_at INTEGER,\n  source TEXT,\n  source_url TEXT,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL,\n  deleted_at INTEGER\n);',
      'CREATE TABLE tags (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL UNIQUE,\n  tag_group TEXT,\n  color TEXT,\n  created_at INTEGER NOT NULL\n);',
      'CREATE TABLE prompt_tags (\n  prompt_id TEXT NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,\n  tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,\n  PRIMARY KEY (prompt_id, tag_id)\n);',
      "CREATE TABLE history (\n  id TEXT PRIMARY KEY,\n  prompt_id TEXT REFERENCES prompts(id) ON DELETE SET NULL,\n  provider_id TEXT NOT NULL,\n  model TEXT NOT NULL,\n  prompt_text TEXT NOT NULL,\n  negative_text TEXT,\n  params TEXT,\n  status TEXT NOT NULL,\n  error_code TEXT,\n  error_message TEXT,\n  image_path TEXT,\n  cost INTEGER,\n  duration_ms INTEGER,\n  created_at INTEGER NOT NULL\n, cost_unit TEXT NOT NULL DEFAULT 'cny_cent');",
      "CREATE TABLE history_prompt_references (\n  history_id TEXT NOT NULL REFERENCES history(id) ON DELETE CASCADE,\n  prompt_id TEXT REFERENCES prompts(id) ON DELETE SET NULL,\n  prompt_title TEXT NOT NULL,\n  excerpt TEXT NOT NULL,\n  scope TEXT NOT NULL CHECK(scope IN ('full', 'excerpt')),\n  sort_order INTEGER NOT NULL,\n  PRIMARY KEY (history_id, sort_order)\n);",
      'CREATE TABLE smart_sets (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  query TEXT NOT NULL,\n  sort_order INTEGER DEFAULT 0,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL\n);',
      'CREATE TABLE search_history (\n  id TEXT PRIMARY KEY,\n  term TEXT NOT NULL UNIQUE,\n  used_at INTEGER NOT NULL\n);',
      'CREATE TABLE providers (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  type TEXT NOT NULL,\n  base_url TEXT NOT NULL,\n  model TEXT NOT NULL,\n  has_key INTEGER DEFAULT 0,\n  key_suffix TEXT,\n  is_active INTEGER DEFAULT 0,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL\n, managed_by TEXT DEFAULT NULL);',
      'CREATE TABLE doubao_web_daily_usage (\n  usage_scope TEXT NOT NULL,\n  usage_date TEXT NOT NULL,\n  request_count INTEGER NOT NULL DEFAULT 0 CHECK(request_count >= 0),\n  updated_at INTEGER NOT NULL,\n  PRIMARY KEY (usage_scope, usage_date)\n);',
      "CREATE VIRTUAL TABLE prompts_fts USING fts5(\n  title, description, content, tags_index,\n  tokenize='unicode61'\n);",
      'CREATE TABLE automation_audit (\n      id INTEGER PRIMARY KEY AUTOINCREMENT,\n      at INTEGER NOT NULL,\n      caller TEXT NOT NULL,\n      action TEXT NOT NULL,\n      prompt_text TEXT,\n      params_json TEXT,\n      estimated_points INTEGER,\n      actual_points INTEGER,\n      approved_via TEXT NOT NULL,\n      status TEXT NOT NULL,\n      job_id TEXT\n    );',
      'CREATE TABLE workbench_sessions (\n      id TEXT PRIMARY KEY,\n      title TEXT NOT NULL CHECK (length(trim(title)) > 0),\n      created_at INTEGER NOT NULL,\n      updated_at INTEGER NOT NULL,\n      archived_at INTEGER,\n      deleted_at INTEGER,\n      CHECK (updated_at >= created_at)\n    );',
      "CREATE TABLE generation_runs (\n      id TEXT PRIMARY KEY,\n      run_kind TEXT NOT NULL CHECK (run_kind IN ('free_generation', 'refinement', 'retry')),\n      workbench_session_id TEXT REFERENCES workbench_sessions(id) ON DELETE SET NULL,\n      workbench_turn_id TEXT,\n      turn_index INTEGER CHECK (turn_index IS NULL OR turn_index >= 0),\n      result_index INTEGER CHECK (result_index IS NULL OR result_index >= 0),\n      parent_run_id TEXT REFERENCES generation_runs(id) ON DELETE SET NULL,\n      retry_of_run_id TEXT REFERENCES generation_runs(id) ON DELETE SET NULL,\n      source_asset_id TEXT,\n      provider_id TEXT NOT NULL CHECK (length(trim(provider_id)) > 0),\n      model TEXT NOT NULL CHECK (length(trim(model)) > 0),\n      user_prompt TEXT NOT NULL DEFAULT '',\n      base_prompt TEXT NOT NULL,\n      refinement_instruction TEXT,\n      final_prompt TEXT NOT NULL CHECK (length(trim(final_prompt)) > 0),\n      negative_prompt TEXT,\n      params_json TEXT NOT NULL CHECK (json_valid(params_json)),\n      prompt_snapshot_json TEXT NOT NULL CHECK (json_valid(prompt_snapshot_json)),\n      status TEXT NOT NULL CHECK (status IN ('queued', 'running', 'success', 'failed', 'cancelled')),\n      error_code TEXT,\n      error_message TEXT,\n      request_id TEXT,\n      estimated_cost REAL,\n      actual_cost REAL,\n      duration_ms INTEGER,\n      created_at INTEGER NOT NULL,\n      started_at INTEGER,\n      finished_at INTEGER,\n      deleted_at INTEGER\n    );",
      "CREATE TABLE generated_assets (\n      id TEXT PRIMARY KEY,\n      run_id TEXT NOT NULL REFERENCES generation_runs(id) ON DELETE CASCADE,\n      position INTEGER NOT NULL CHECK (position >= 0),\n      status TEXT NOT NULL CHECK (status IN ('available', 'missing', 'deleted', 'failed')),\n      media_path TEXT,\n      mime_type TEXT,\n      width INTEGER,\n      height INTEGER,\n      file_size INTEGER,\n      checksum TEXT,\n      created_at INTEGER NOT NULL,\n      UNIQUE (run_id, position)\n    );",
      "CREATE TABLE cloud_sync_accounts (\n      owner_id TEXT PRIMARY KEY,\n      username TEXT NOT NULL,\n      device_id TEXT NOT NULL,\n      device_name TEXT NOT NULL,\n      platform TEXT NOT NULL CHECK (platform IN ('macos', 'windows', 'linux')),\n      client_version TEXT NOT NULL,\n      active INTEGER NOT NULL DEFAULT 0 CHECK (active IN (0, 1)),\n      enabled INTEGER NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),\n      cursor TEXT NOT NULL DEFAULT '0' CHECK (cursor GLOB '[0-9]*'),\n      bootstrap_completed_at INTEGER,\n      last_sync_at INTEGER,\n      last_error TEXT,\n      created_at INTEGER NOT NULL,\n      updated_at INTEGER NOT NULL,\n      UNIQUE(owner_id, device_id)\n    );",
      "CREATE TABLE cloud_entity_state (\n      owner_id TEXT NOT NULL REFERENCES cloud_sync_accounts(owner_id) ON DELETE CASCADE,\n      entity_type TEXT NOT NULL CHECK (entity_type IN ('prompt', 'folder', 'tag')),\n      local_id TEXT NOT NULL,\n      cloud_id TEXT NOT NULL,\n      cloud_version INTEGER CHECK (cloud_version IS NULL OR cloud_version > 0),\n      last_synced_hash TEXT,\n      remote_snapshot_json TEXT CHECK (remote_snapshot_json IS NULL OR json_valid(remote_snapshot_json)),\n      sync_status TEXT NOT NULL CHECK (sync_status IN ('clean', 'pending', 'conflict', 'error')),\n      last_synced_at INTEGER,\n      PRIMARY KEY(owner_id, entity_type, local_id),\n      UNIQUE(owner_id, entity_type, cloud_id)\n    );",
      "CREATE TABLE cloud_sync_outbox (\n      mutation_id TEXT PRIMARY KEY,\n      owner_id TEXT NOT NULL REFERENCES cloud_sync_accounts(owner_id) ON DELETE CASCADE,\n      entity_type TEXT NOT NULL CHECK (entity_type IN ('prompt', 'folder', 'tag')),\n      entity_id TEXT NOT NULL,\n      operation TEXT NOT NULL CHECK (operation IN ('create', 'update', 'delete', 'restore')),\n      base_version INTEGER CHECK (base_version IS NULL OR base_version > 0),\n      payload_json TEXT NOT NULL CHECK (json_valid(payload_json)),\n      created_at INTEGER NOT NULL,\n      attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),\n      next_attempt_at INTEGER NOT NULL DEFAULT 0,\n      last_error TEXT\n    );",
      "CREATE TABLE cloud_sync_conflicts (\n      id TEXT PRIMARY KEY,\n      owner_id TEXT NOT NULL REFERENCES cloud_sync_accounts(owner_id) ON DELETE CASCADE,\n      entity_type TEXT NOT NULL CHECK (entity_type IN ('prompt', 'folder', 'tag')),\n      entity_id TEXT NOT NULL,\n      mutation_id TEXT NOT NULL,\n      base_version INTEGER,\n      local_snapshot_json TEXT NOT NULL CHECK (json_valid(local_snapshot_json)),\n      remote_snapshot_json TEXT NOT NULL CHECK (json_valid(remote_snapshot_json)),\n      detected_at INTEGER NOT NULL,\n      resolved_at INTEGER,\n      resolution TEXT CHECK (resolution IS NULL OR resolution IN ('remote', 'local', 'duplicate'))\n    );",
      "CREATE TABLE cloud_sync_usage_outbox (\n      event_id TEXT PRIMARY KEY,\n      owner_id TEXT NOT NULL REFERENCES cloud_sync_accounts(owner_id) ON DELETE CASCADE,\n      prompt_id TEXT NOT NULL,\n      action TEXT NOT NULL CHECK (action IN ('copy', 'apply', 'generate')),\n      created_at INTEGER NOT NULL,\n      attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),\n      next_attempt_at INTEGER NOT NULL DEFAULT 0,\n      last_error TEXT\n    );",
      'CREATE INDEX idx_folders_parent ON folders(parent_id);',
      'CREATE INDEX idx_folders_sort ON folders(sort_order);',
      'CREATE INDEX idx_prompts_folder ON prompts(folder_id) WHERE deleted_at IS NULL;',
      'CREATE INDEX idx_prompts_model ON prompts(model_id) WHERE deleted_at IS NULL;',
      'CREATE INDEX idx_prompts_pinned ON prompts(is_pinned, pin_order) WHERE deleted_at IS NULL AND is_pinned = 1;',
      'CREATE INDEX idx_prompts_updated ON prompts(updated_at DESC) WHERE deleted_at IS NULL;',
      'CREATE INDEX idx_tags_group ON tags(tag_group);',
      'CREATE INDEX idx_prompt_tags_tag ON prompt_tags(tag_id);',
      'CREATE INDEX idx_history_created ON history(created_at DESC);',
      'CREATE INDEX idx_history_prompt ON history(prompt_id);',
      'CREATE INDEX idx_history_status ON history(status);',
      'CREATE INDEX idx_history_prompt_refs_prompt\n  ON history_prompt_references(prompt_id);',
      'CREATE INDEX idx_history_prompt_refs_history\n  ON history_prompt_references(history_id, sort_order);',
      'CREATE INDEX idx_smart_sets_sort ON smart_sets(sort_order, created_at DESC);',
      'CREATE INDEX idx_search_history_used ON search_history(used_at DESC);',
      'CREATE INDEX idx_automation_audit_at ON automation_audit(at DESC);',
      'CREATE INDEX idx_workbench_sessions_active_updated\n      ON workbench_sessions(archived_at, updated_at DESC)\n      WHERE deleted_at IS NULL;',
      'CREATE INDEX idx_generation_runs_workbench_order\n      ON generation_runs(workbench_session_id, turn_index, result_index, created_at)\n      WHERE workbench_session_id IS NOT NULL AND deleted_at IS NULL;',
      'CREATE INDEX idx_generation_runs_parent_created\n      ON generation_runs(parent_run_id, created_at ASC)\n      WHERE parent_run_id IS NOT NULL;',
      'CREATE INDEX idx_generation_runs_status_created\n      ON generation_runs(status, created_at DESC);',
      'CREATE INDEX idx_generated_assets_run_position\n      ON generated_assets(run_id, position);',
      'CREATE INDEX idx_generated_assets_media_path\n      ON generated_assets(media_path) WHERE media_path IS NOT NULL;',
      'CREATE UNIQUE INDEX idx_cloud_sync_one_active_account\n      ON cloud_sync_accounts(active) WHERE active = 1;',
      'CREATE INDEX idx_cloud_entity_state_status\n      ON cloud_entity_state(owner_id, sync_status, entity_type);',
      'CREATE INDEX idx_cloud_sync_outbox_ready\n      ON cloud_sync_outbox(owner_id, next_attempt_at, created_at, mutation_id);',
      'CREATE INDEX idx_cloud_sync_outbox_entity\n      ON cloud_sync_outbox(owner_id, entity_type, entity_id, created_at);',
      'CREATE UNIQUE INDEX idx_cloud_sync_conflicts_active_entity\n      ON cloud_sync_conflicts(owner_id, entity_type, entity_id)\n      WHERE resolved_at IS NULL;',
      'CREATE INDEX idx_cloud_sync_conflicts_owner_detected\n      ON cloud_sync_conflicts(owner_id, resolved_at, detected_at DESC);',
      'CREATE INDEX idx_cloud_sync_usage_outbox_ready\n      ON cloud_sync_usage_outbox(owner_id, next_attempt_at, created_at, event_id);',
    ],
    bps: true,
    folderMillis: 1787936392750,
    hash: 'b706c14e8ef5b827bff1ebec46700a6c80f4d47553691654ffc6ad884810f445',
  },
  {
    sql: [
      'CREATE TABLE `workbench_drafts` (\n\t`session_id` text PRIMARY KEY NOT NULL,\n\t`draft_json` text NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `workbench_sessions`(`id`) ON UPDATE no action ON DELETE cascade\n);',
    ],
    bps: true,
    folderMillis: 1787936645137,
    hash: 'eb58f87918941e75a74a9652bf2a48dc4153170aa4a5534a7e8eea7fd3d5c2c3',
  },
  {
    sql: [
      'ALTER TABLE `generation_runs` ADD `prompt_id` text;',
      'CREATE INDEX `idx_generation_runs_prompt_created` ON `generation_runs` (`prompt_id`,`created_at`) WHERE prompt_id IS NOT NULL;',
      "-- 单账本回填(V25 生命周期决议:generation_runs 是唯一生成账本):\n-- history 旧行按同 id 迁入 generation_runs;双写期两边同 id,已存在的跳过(幂等)。\n-- 语义映射:\n--   * created_at:旧 history 在生成完成时写入,故同时充当 finished_at;started_at 留空(未知)。\n--   * cost:cost_unit='point' 原值即积分;'cny_cent'(BYOK 分)换算为元(÷100)。\n--   * 空 prompt/provider/model 用占位符满足 CHECK 约束;非法 status 归并为 failed。\n--   * history_prompt_references 内嵌进 prompt_snapshot_json.promptReferences(快照语义不变)。\nINSERT INTO generation_runs (\n  id, run_kind, prompt_id, provider_id, model,\n  user_prompt, base_prompt, final_prompt, negative_prompt,\n  params_json, prompt_snapshot_json,\n  status, error_code, error_message, actual_cost, duration_ms,\n  created_at, finished_at\n)\nSELECT\n  h.id,\n  'free_generation',\n  h.prompt_id,\n  CASE WHEN length(trim(h.provider_id)) > 0 THEN h.provider_id ELSE 'unknown' END,\n  CASE WHEN length(trim(h.model)) > 0 THEN h.model ELSE 'unknown' END,\n  h.prompt_text,\n  CASE WHEN length(trim(h.prompt_text)) > 0 THEN h.prompt_text ELSE '(未记录提示词)' END,\n  CASE WHEN length(trim(h.prompt_text)) > 0 THEN h.prompt_text ELSE '(未记录提示词)' END,\n  h.negative_text,\n  CASE WHEN h.params IS NOT NULL AND json_valid(h.params) THEN h.params ELSE '{\"schemaVersion\":1}' END,\n  json_object(\n    'schemaVersion', 1,\n    'userPrompt', h.prompt_text,\n    'basePrompt', CASE WHEN length(trim(h.prompt_text)) > 0 THEN h.prompt_text ELSE '(未记录提示词)' END,\n    'refinementInstruction', NULL,\n    'finalPrompt', CASE WHEN length(trim(h.prompt_text)) > 0 THEN h.prompt_text ELSE '(未记录提示词)' END,\n    'negativePrompt', h.negative_text,\n    'promptReferences', json(COALESCE((\n      SELECT json_group_array(json_object(\n        'promptId', r.prompt_id,\n        'title', r.prompt_title,\n        'excerpt', r.excerpt,\n        'scope', r.scope\n      ) ORDER BY r.sort_order)\n      FROM history_prompt_references r\n      WHERE r.history_id = h.id\n    ), '[]'))\n  ),\n  CASE WHEN h.status IN ('success', 'failed', 'cancelled') THEN h.status ELSE 'failed' END,\n  h.error_code,\n  h.error_message,\n  CASE\n    WHEN h.cost IS NULL THEN NULL\n    WHEN h.cost_unit = 'cny_cent' THEN h.cost / 100.0\n    ELSE h.cost\n  END,\n  h.duration_ms,\n  h.created_at,\n  h.created_at\nFROM history h\nWHERE NOT EXISTS (SELECT 1 FROM generation_runs gr WHERE gr.id = h.id);",
      "-- 成功行的出图落为 position 0 资产(资产 id 沿用 run id,与 runs.complete 的约定一致)。\nINSERT INTO generated_assets (id, run_id, position, status, media_path, created_at)\nSELECT h.id, h.id, 0, 'available', h.image_path, h.created_at\nFROM history h\nWHERE h.image_path IS NOT NULL\n  AND h.status = 'success'\n  AND NOT EXISTS (SELECT 1 FROM generated_assets ga WHERE ga.run_id = h.id AND ga.position = 0)\n  AND NOT EXISTS (SELECT 1 FROM generated_assets ga2 WHERE ga2.id = h.id);",
    ],
    bps: true,
    folderMillis: 1788013036888,
    hash: '6f712290dd5f03cd0a48e632e99b78a615cb04dfaffbe1d1b87555371f343326',
  },
  {
    sql: ['DROP TABLE `history_prompt_references`;', 'DROP TABLE `history`;'],
    bps: true,
    folderMillis: 1788013114959,
    hash: '94687ce1de5b693f9e4148fdbb11dedfcc88a3be4200602ea254c65a686e63bf',
  },
];
