// packages/desktop-contracts/src/ipc/channels.ts
// IPC 通道名常量（V13-GOV-04 自 ipc.ts 分域拆出）。preload 与渲染进程都依赖。

// ---------- 通道名常量 ----------
export const IPC = {
  // prompts
  PROMPTS_LIST: "db:prompts:list",
  PROMPTS_GET: "db:prompts:get",
  PROMPTS_CREATE: "db:prompts:create",
  PROMPTS_UPDATE: "db:prompts:update",
  PROMPTS_DELETE: "db:prompts:delete",
  PROMPTS_TOGGLE_PIN: "db:prompts:togglePin",
  PROMPTS_REORDER_PINS: "db:prompts:reorderPins",
  PROMPTS_INCREMENT_USAGE: "db:prompts:incrementUsage",
  // 回收站（docs/product/10 TASK-LIB-12）
  PROMPTS_LIST_DELETED: "db:prompts:listDeleted",
  PROMPTS_RESTORE: "db:prompts:restore",
  PROMPTS_PURGE: "db:prompts:purge",
  PROMPTS_PURGE_ALL: "db:prompts:purgeAll",
  PROMPTS_STATS: "db:prompts:stats",
  // search history（docs/product/15 TASK-DIF-06；智能集 IPC 已退役）
  SEARCH_HISTORY_LIST: "db:searchHistory:list",
  SEARCH_HISTORY_ADD: "db:searchHistory:add",
  SEARCH_HISTORY_CLEAR: "db:searchHistory:clear",
  WORKBENCH_SESSION_ENSURE: "workbenchSession:ensure",
  WORKBENCH_SESSION_LIST: "workbenchSession:list",
  WORKBENCH_SESSION_GET: "workbenchSession:get",
  WORKBENCH_SESSION_RENAME: "workbenchSession:rename",
  WORKBENCH_SESSION_ARCHIVE: "workbenchSession:archive",
  WORKBENCH_SESSION_DELETE: "workbenchSession:delete",
  SKILL_RUNTIME_PREPARE_GITHUB: "skillRuntime:prepareGithub",
  SKILL_RUNTIME_EXECUTE: "skillRuntime:execute",
  SKILL_RUNTIME_CANCEL: "skillRuntime:cancel",
  SKILL_RUNTIME_RELEASE: "skillRuntime:release",
  /** 主进程 → 渲染进程的 Skill 执行事件（流式文本 / 工具调用 / 生图结果） */
  SKILL_RUNTIME_EVENT: "skillRuntime:event",
  // v0.3.2 设计方案 Runtime（创建切片）
  DESIGN_SCHEME_CREATE_START: "designScheme:create:start",
  DESIGN_SCHEME_CREATE_CONFIRM_INSTALL: "designScheme:create:confirmInstall",
  DESIGN_SCHEME_CREATE_CANCEL: "designScheme:create:cancel",
  DESIGN_SCHEME_LIST: "designScheme:list",
  DESIGN_SCHEME_GET_REVISION: "designScheme:getRevision",
  DESIGN_SCHEME_LIST_ASSETS: "designScheme:listAssets",
  DESIGN_SCHEME_UPDATE_INPUTS: "designScheme:updateInputs",
  DESIGN_SCHEME_RUN_START: "designScheme:run:start",
  DESIGN_SCHEME_RUN_CANCEL: "designScheme:run:cancel",
  DESIGN_SCHEME_SELECT_COVER: "designScheme:selectCover",
  DESIGN_SCHEME_FORMALIZE: "designScheme:formalize",
  DESIGN_SCHEME_RENAME: "designScheme:rename",
  DESIGN_SCHEME_REMOVE: "designScheme:remove",
  DESIGN_SCHEME_LIST_SOURCE_FILES: "designScheme:listSourceFiles",
  DESIGN_SCHEME_MODIFY_START: "designScheme:modify:start",
  DESIGN_SCHEME_MODIFY_CANCEL: "designScheme:modify:cancel",
  DESIGN_SCHEME_PROMOTE_DRAFT: "designScheme:promoteDraft",
  DESIGN_SCHEME_CHECK_UPDATE: "designScheme:checkUpdate",
  DESIGN_SCHEME_MARKET_SEARCH: "designScheme:marketSearch",
  DESIGN_SCHEME_EXPORT: "designScheme:export",
  DESIGN_SCHEME_IMPORT: "designScheme:import",
  /** 主进程 → 渲染进程的方案创建事件（状态机 / 轨迹 / 安装确认 / 草稿就绪） */
  DESIGN_SCHEME_EVENT: "designScheme:event",
  // BYOK text AI connections and design assistants
  AI_CONNECTION_LIST_PRESETS: "aiConnection:listPresets",
  AI_CONNECTION_LIST: "aiConnection:list",
  AI_CONNECTION_CREATE: "aiConnection:create",
  AI_CONNECTION_UPDATE: "aiConnection:update",
  AI_CONNECTION_DELETE: "aiConnection:delete",
  AI_CONNECTION_SAVE_KEY: "aiConnection:saveKey",
  AI_CONNECTION_DELETE_KEY: "aiConnection:deleteKey",
  AI_CONNECTION_HAS_KEY: "aiConnection:hasKey",
  AI_CONNECTION_SET_ACTIVE: "aiConnection:setActive",
  AI_CONNECTION_LIST_MODELS: "aiConnection:listModels",
  AI_CONNECTION_VALIDATE: "aiConnection:validate",
  // providers
  PROVIDER_LIST: "provider:list",
  PROVIDER_CREATE: "provider:create",
  PROVIDER_UPDATE: "provider:update",
  PROVIDER_DELETE: "provider:delete",
  PROVIDER_SAVE_KEY: "provider:saveKey",
  PROVIDER_HAS_KEY: "provider:hasKey",
  PROVIDER_OPEN_WEB_LOGIN: "provider:openWebLogin",
  PROVIDER_WEB_LOGIN_START: "provider:webLoginStart",
  PROVIDER_WEB_LOGIN_REFRESH: "provider:webLoginRefresh",
  PROVIDER_WEB_LOGOUT: "provider:webLogout",
  PROVIDER_WEB_LOGIN_STATE: "provider:webLoginState",
  PROVIDER_WEB_LOGIN_CHANGED: "provider:webLoginChanged",
  PROVIDER_WEB_DEVELOPER_VISIBLE: "provider:setWebDeveloperVisible",
  PROVIDER_WEB_USAGE: "provider:webUsage",
  PROVIDER_WEB_STATUS: "provider:webStatus",
  PROVIDER_VALIDATE: "provider:validate",
  PROVIDER_LIST_MODELS: "provider:listModels",
  PROVIDER_SET_ACTIVE: "provider:setActive",
  // one-shot file:// → app://musefold localStorage import (preload-only; not on window.api)
  PREFS_PULL_ORIGIN_MIGRATION: "prefs:pullOriginMigration",
  PREFS_ORIGIN_MIGRATION_APPLIED: "prefs:originMigrationApplied",
  // images
  IMAGE_GENERATE: "image:generate",
  IMAGE_PICK_LOCAL: "image:pickLocal",
  IMAGE_STAGE_LOCAL: "image:stageLocal",
  IMAGE_CANCEL: "image:cancel",
  IMAGE_RETRY: "image:retry",
  IMAGE_PROGRESS: "image:progress",
  // history
  HISTORY_LIST: "db:history:list",
  HISTORY_RELATED: "db:history:related",
  HISTORY_LINK_PROMPT: "db:history:linkPrompt",
  HISTORY_GET: "db:history:get",
  HISTORY_DELETE: "db:history:delete",
  HISTORY_CLEAR: "db:history:clear",
  HISTORY_STATS: "db:history:stats",
  // system
  SYSTEM_GET_PATHS: "system:getPaths",
  SYSTEM_GET_VERSION: "system:getVersion",
  SYSTEM_OPEN_ABOUT_RESOURCE: "system:openAboutResource",
  SYSTEM_OPEN_IN_FOLDER: "system:openInFolder",
  SYSTEM_SAVE_IMAGE: "system:saveImage",
  SYSTEM_SAVE_IMAGES: "system:saveImages",
  SYSTEM_COPY_IMAGE: "system:copyImage",
  SYSTEM_READ_CLIPBOARD_TEXT: "system:readClipboardText",
  SYSTEM_READ_CLIPBOARD_IMAGE: "system:readClipboardImage",
  AUTOMATION_STATUS: "automation:status",
  AUTOMATION_SET_ENABLED: "automation:setEnabled",
  AUTOMATION_ROTATE_TOKEN: "automation:rotateToken",
  AUTOMATION_AUDIT_LIST: "automation:auditList",
  // v0.5 账号与云通道（V05-ACC-05；docs/v0.5/V05-ARCHITECTURE.md §7）
  ACCOUNT_STATUS: "account:status",
  ACCOUNT_REGISTER: "account:register",
  ACCOUNT_LOGIN: "account:login",
  ACCOUNT_LOGOUT: "account:logout",
  ACCOUNT_REDEEM: "account:redeem",
  ACCOUNT_REFRESH_QUOTA: "account:refreshQuota",
  ACCOUNT_SET_SERVER_URL: "account:setServerUrl",
  /** 主进程 → 渲染进程：登录/登出/额度/健康度/公告变化 */
  ACCOUNT_CHANGED: "account:changed",
  CLOUD_SYNC_STATUS: "cloudSync:status",
  CLOUD_SYNC_SET_ENABLED: "cloudSync:setEnabled",
  CLOUD_SYNC_NOW: "cloudSync:now",
  CLOUD_SYNC_CONFLICTS: "cloudSync:conflicts",
  CLOUD_SYNC_RESOLVE: "cloudSync:resolve",
  CLOUD_SYNC_CHANGED: "cloudSync:changed",
  CLOUD_CONNECTIONS_LIST: "cloudConnections:list",
  CLOUD_CONNECTIONS_UPDATE: "cloudConnections:update",
  CLOUD_CONNECTIONS_REVOKE: "cloudConnections:revoke",
  AUTOMATION_CONFIRM: "automation:confirm",
  AUTOMATION_BUDGET_GET: "automation:budgetGet",
  AUTOMATION_BUDGET_SET: "automation:budgetSet",
  AUTOMATION_CONFIRMATION_REQUIRED: "automation:confirmationRequired",
  AUTOMATION_CONFIRMATION_RESOLVED: "automation:confirmationResolved",
  AUTOMATION_ACTIVITY: "automation:activity",
  /** 控制面只负责唤起原生配置页；凭据仍由用户在渲染层输入。 */
  AUTOMATION_SETUP_REQUESTED: "automation:setupRequested",
  AUTOMATION_PROVIDER_CHANGED: "automation:providerChanged",
  AUTOMATION_INTEGRATION_INFO: "automation:integrationInfo",
  AUTOMATION_INTEGRATION_ACTION: "automation:integrationAction",
  SYSTEM_DISK_USAGE: "system:diskUsage",
  SYSTEM_EXPORT: "system:export",
  SYSTEM_IMPORT: "system:import",
  SYSTEM_LIST_BACKUPS: "system:listBackups",
  SYSTEM_BACKUP_NOW: "system:backupNow",
  SYSTEM_RESTORE_BACKUP: "system:restoreBackup",
  SYSTEM_RELAUNCH: "system:relaunch",
  SYSTEM_RESET_DATA: "system:resetData",
  // application updates
  UPDATER_GET_STATE: "updater:getState",
  UPDATER_CHECK: "updater:check",
  UPDATER_DOWNLOAD: "updater:download",
  UPDATER_INSTALL: "updater:install",
  UPDATER_GET_CHANNEL: "updater:getChannel",
  UPDATER_SET_CHANNEL: "updater:setChannel",
  UPDATER_STATE_CHANGED: "updater:stateChanged",
  /** 内容层启动信标：渲染进程首帧完成且 IPC 可用。单向 send，无应答。 */
  UPDATER_CONTENT_READY: "updater:contentReady",
  /** 内容层窄状态：版本 / 来源 / 脱敏检查结果。无入参。 */
  UPDATER_GET_CONTENT_STATE: "updater:getContentState",
  /** 手动触发一次内容层检查；后续 E2E 的确定性触发点。无入参。 */
  UPDATER_CHECK_CONTENT_NOW: "updater:checkContentNow",
  // share / deeplink（docs/product/15 TASK-DIF-05）
  SHARE_RENDER_CARD: "share:renderCard",
  SHARE_BUILD_DEEPLINK: "share:buildDeeplink",
  SHARE_PARSE_DEEPLINK: "share:parseDeeplink",
  SHARE_IMPORT: "share:import",
  SHARE_CONSUME_PENDING: "share:consumePending",
  SHARE_INCOMING: "share:incoming",
  // logs
  LOG_TAIL: "log:tail",
  LOG_OPEN_DIR: "log:openDir",
  // 桌宠（悬浮伴侣）：纯表现层，只消费生图活动快照
  PET_SET_ENABLED: "pet:setEnabled",
  PET_IS_ENABLED: "pet:isEnabled",
  PET_GET_FRAME: "pet:getFrame",
  PET_FRAME: "pet:frame",
  PET_READY: "pet:ready",
  PET_INTERACT: "pet:interact",
  PET_MOVE_BY: "pet:moveBy",
  PET_RUN_TO_COMPOSER: "pet:runToComposer",
  PET_RETURN_HOME: "pet:returnHome",
  PET_MENU: "pet:menu",
  // global diagnostics event (main/preload -> renderer)
  DIAGNOSTICS_ERROR: "diagnostics:error",
} as const;
