import { z } from 'zod';
export declare const entityIdSchema: z.ZodString;
export declare const isoDateTimeSchema: z.ZodString;
export declare const paginationCursorSchema: z.ZodString;
/**
 * GET 查询串字段的宽容输入(替代 z.coerce:coerce 的 z.input 是 unknown,
 * 会污染 gateway/api-client 的方法签名)。程序侧传原生类型,wire 侧传字符串。
 */
export declare const queryIntegerSchema: z.ZodUnion<
  readonly [z.ZodNumber, z.ZodPipe<z.ZodString, z.ZodTransform<number, string>>]
>;
export declare const queryBooleanSchema: z.ZodUnion<
  readonly [
    z.ZodBoolean,
    z.ZodPipe<
      z.ZodEnum<{
        true: 'true';
        false: 'false';
      }>,
      z.ZodTransform<boolean, 'true' | 'false'>
    >,
  ]
>;
export declare const apiErrorCodeSchema: z.ZodEnum<{
  AUTH_REQUIRED: 'AUTH_REQUIRED';
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED';
  AUTH_CREDENTIALS_INVALID: 'AUTH_CREDENTIALS_INVALID';
  AUTH_REGISTRATION_DISABLED: 'AUTH_REGISTRATION_DISABLED';
  OAUTH_INVALID_GRANT: 'OAUTH_INVALID_GRANT';
  OAUTH_SCOPE_INSUFFICIENT: 'OAUTH_SCOPE_INSUFFICIENT';
  ACCOUNT_QUOTA_INSUFFICIENT: 'ACCOUNT_QUOTA_INSUFFICIENT';
  ACCOUNT_REDEEM_INVALID: 'ACCOUNT_REDEEM_INVALID';
  PROMPT_NOT_FOUND: 'PROMPT_NOT_FOUND';
  PROMPT_VERSION_CONFLICT: 'PROMPT_VERSION_CONFLICT';
  SYNC_CURSOR_EXPIRED: 'SYNC_CURSOR_EXPIRED';
  SYNC_MUTATION_CONFLICT: 'SYNC_MUTATION_CONFLICT';
  WORKBENCH_SESSION_NOT_FOUND: 'WORKBENCH_SESSION_NOT_FOUND';
  WORKBENCH_VERSION_CONFLICT: 'WORKBENCH_VERSION_CONFLICT';
  GENERATION_NOT_FOUND: 'GENERATION_NOT_FOUND';
  GENERATION_ALREADY_TERMINAL: 'GENERATION_ALREADY_TERMINAL';
  GENERATION_UPSTREAM_REJECTED: 'GENERATION_UPSTREAM_REJECTED';
  GENERATION_UPSTREAM_UNKNOWN: 'GENERATION_UPSTREAM_UNKNOWN';
  GENERATION_STORAGE_FAILED: 'GENERATION_STORAGE_FAILED';
  GENERATION_APPROVAL_REQUIRED: 'GENERATION_APPROVAL_REQUIRED';
  GENERATION_APPROVAL_EXPIRED: 'GENERATION_APPROVAL_EXPIRED';
  MCP_BUDGET_EXCEEDED: 'MCP_BUDGET_EXCEEDED';
  RATE_LIMITED: 'RATE_LIMITED';
  VALIDATION_FAILED: 'VALIDATION_FAILED';
  INTERNAL_ERROR: 'INTERNAL_ERROR';
}>;
export declare const apiErrorResponseSchema: z.ZodObject<
  {
    error: z.ZodObject<
      {
        code: z.ZodEnum<{
          AUTH_REQUIRED: 'AUTH_REQUIRED';
          AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED';
          AUTH_CREDENTIALS_INVALID: 'AUTH_CREDENTIALS_INVALID';
          AUTH_REGISTRATION_DISABLED: 'AUTH_REGISTRATION_DISABLED';
          OAUTH_INVALID_GRANT: 'OAUTH_INVALID_GRANT';
          OAUTH_SCOPE_INSUFFICIENT: 'OAUTH_SCOPE_INSUFFICIENT';
          ACCOUNT_QUOTA_INSUFFICIENT: 'ACCOUNT_QUOTA_INSUFFICIENT';
          ACCOUNT_REDEEM_INVALID: 'ACCOUNT_REDEEM_INVALID';
          PROMPT_NOT_FOUND: 'PROMPT_NOT_FOUND';
          PROMPT_VERSION_CONFLICT: 'PROMPT_VERSION_CONFLICT';
          SYNC_CURSOR_EXPIRED: 'SYNC_CURSOR_EXPIRED';
          SYNC_MUTATION_CONFLICT: 'SYNC_MUTATION_CONFLICT';
          WORKBENCH_SESSION_NOT_FOUND: 'WORKBENCH_SESSION_NOT_FOUND';
          WORKBENCH_VERSION_CONFLICT: 'WORKBENCH_VERSION_CONFLICT';
          GENERATION_NOT_FOUND: 'GENERATION_NOT_FOUND';
          GENERATION_ALREADY_TERMINAL: 'GENERATION_ALREADY_TERMINAL';
          GENERATION_UPSTREAM_REJECTED: 'GENERATION_UPSTREAM_REJECTED';
          GENERATION_UPSTREAM_UNKNOWN: 'GENERATION_UPSTREAM_UNKNOWN';
          GENERATION_STORAGE_FAILED: 'GENERATION_STORAGE_FAILED';
          GENERATION_APPROVAL_REQUIRED: 'GENERATION_APPROVAL_REQUIRED';
          GENERATION_APPROVAL_EXPIRED: 'GENERATION_APPROVAL_EXPIRED';
          MCP_BUDGET_EXCEEDED: 'MCP_BUDGET_EXCEEDED';
          RATE_LIMITED: 'RATE_LIMITED';
          VALIDATION_FAILED: 'VALIDATION_FAILED';
          INTERNAL_ERROR: 'INTERNAL_ERROR';
        }>;
        message: z.ZodString;
        requestId: z.ZodString;
        retryable: z.ZodBoolean;
        details: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
      },
      z.core.$strip
    >;
  },
  z.core.$strip
>;
export type ApiErrorCode = z.infer<typeof apiErrorCodeSchema>;
export type ApiErrorResponse = z.infer<typeof apiErrorResponseSchema>;
//# sourceMappingURL=common.d.ts.map
